# Default values for lingvis-server
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

Group: dbvis
Project: covid-19-vis-backend
Branch: master

urlProtocol: https

cpu:
  req: 500m
  limit: 1000m

mem:
  req: 1Gi
  limit: 2Gi